"""Add User table

Revision ID: 4482f5a1c54e
Revises: 397634b2c847
Create Date: 2026-03-12 22:16:57.137225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4482f5a1c54e'
down_revision = '397634b2c847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
